# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.Edge
PackageVersion: 141.0.3537.92
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- msedge
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
AppsAndFeaturesEntries:
- UpgradeCode: '{883C2625-37F7-357F-A0F4-DFAF391B2B9C}'
Installers:
- Architecture: x86
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/74538441-4544-4fad-a590-716b3b497f2a/MicrosoftEdgeEnterpriseX86.msi
  InstallerSha256: 46CD9CC3E464C467C9CA30A82FC6F47F48ABD11DABCA5B55496970FB06BADEB9
  ProductCode: '{17485D6F-6B08-3351-8F97-1F7F0860FFDE}'
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/b7be1f33-424d-4f47-83bc-f1b4f42ef0c0/MicrosoftEdgeEnterpriseX64.msi
  InstallerSha256: F42BF3C00B47994AA4B19C44F110F523E28234487E182AF7FE7538A5C9BD0B54
  ProductCode: '{E210A98C-C19E-3F08-B199-7ABF723EE4AE}'
- Architecture: arm64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/fd8afe3a-e2e5-4631-913b-1e2619b63cae/MicrosoftEdgeEnterpriseARM64.msi
  InstallerSha256: CC0AA5B5B732D7A594DF648D741EB94A793366C6CDEF40590C5F1F1250AD49D9
  ProductCode: '{5953DA12-7396-3633-B336-1C2E361CA468}'
ManifestType: installer
ManifestVersion: 1.10.0
